# Generated by Django 3.0.5 on 2020-05-10 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0003_auto_20200510_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 18, 8, 28, 947780)),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 18, 8, 28, 948398)),
        ),
    ]
