# Generated by Django 3.0.5 on 2020-05-10 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0004_auto_20200510_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='level',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 18, 13, 39, 127114)),
        ),
    ]
