# Generated by Django 3.0.5 on 2020-05-10 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0005_auto_20200510_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='level',
            name='text',
        ),
        migrations.AddField(
            model_name='level',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 18, 29, 5, 169095)),
        ),
    ]
