# Generated by Django 3.0.5 on 2020-05-10 18:58

import datetime
from django.db import migrations, models
import oth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0009_auto_20200510_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(default='images/level1.jpg', upload_to=oth.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 18, 58, 50, 103856)),
        ),
    ]
