# Generated by Django 3.0.5 on 2020-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0010_auto_20200510_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
