# Generated by Django 3.0.5 on 2020-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0011_auto_20200510_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
