# Generated by Django 3.0.5 on 2020-05-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0013_auto_20200510_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='l_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oth.Level'),
        ),
    ]
