# Generated by Django 3.0.5 on 2020-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0014_auto_20200510_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default='images/level1.jpg', null=True, upload_to='images/'),
        ),
    ]
