# Generated by Django 3.0.5 on 2020-05-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0019_auto_20200510_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='l_number',
        ),
    ]
