# Generated by Django 3.0.5 on 2020-05-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0020_remove_level_l_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='l_number',
            new_name='level',
        ),
    ]
