# Generated by Django 3.0.5 on 2020-05-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0021_auto_20200510_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='max_level',
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
