# Generated by Django 3.0.5 on 2020-05-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0022_auto_20200510_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='Question',
        ),
    ]
