# Generated by Django 3.0.5 on 2020-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0024_auto_20200510_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.AddField(
            model_name='player',
            name='random_number',
            field=models.IntegerField(default=1),
        ),
    ]
