# Generated by Django 3.0.5 on 2020-05-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0026_auto_20200511_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sentiment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
