# Generated by Django 3.0.5 on 2020-05-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0027_auto_20200511_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
