# Generated by Django 2.2.12 on 2020-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0029_emotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='player',
            name='player_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
