# Generated by Django 2.2.16 on 2020-09-12 15:27

from django.db import migrations, models
import oth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0031_auto_20200517_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='videofile',
            field=models.FileField(null=True, upload_to=oth.models.get_upload_path),
        ),
    ]
