# Generated by Django 2.2.16 on 2020-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0032_question_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
