# Generated by Django 2.2.16 on 2020-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0033_question_video_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video_viewed',
        ),
        migrations.AddField(
            model_name='player',
            name='video_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
