# Generated by Django 2.2.16 on 2020-09-13 15:02

from django.db import migrations, models
import oth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0036_auto_20200913_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='images/level1.jpg', null=True, upload_to=oth.models.get_upload_path),
        ),
    ]
