# Generated by Django 2.2.16 on 2020-09-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0038_question_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='score',
            new_name='option1_score',
        ),
        migrations.AddField(
            model_name='question',
            name='option2_score',
            field=models.IntegerField(default=0),
        ),
    ]
