# Generated by Django 2.2.16 on 2020-09-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0039_auto_20200913_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1_score',
            new_name='option1_level_score',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2_score',
            new_name='option2_level_score',
        ),
        migrations.AddField(
            model_name='player',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oth.Module'),
            preserve_default=False,
        ),
    ]
