# Generated by Django 2.2.16 on 2020-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0040_auto_20200915_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='module',
        ),
        migrations.AddField(
            model_name='player',
            name='base_module_level',
            field=models.IntegerField(default=0),
        ),
    ]
