# Generated by Django 2.2.16 on 2020-09-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0041_auto_20200915_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='base_module_level',
        ),
        migrations.AddField(
            model_name='player',
            name='base_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oth.Module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oth.Module'),
        ),
    ]
