# Generated by Django 2.2.16 on 2020-09-15 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0042_auto_20200915_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='base_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oth.Module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oth.Module'),
        ),
    ]
