# Generated by Django 2.2.16 on 2020-09-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0043_auto_20200915_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module',
            new_name='module_name',
        ),
        migrations.AddField(
            model_name='module',
            name='module_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
