# Generated by Django 2.2.16 on 2020-09-19 15:56

from django.db import migrations, models
import oth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0044_auto_20200915_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audiofile',
            field=models.FileField(blank=True, null=True, upload_to=oth.models.get_upload_path),
        ),
    ]
